### ISSUE TITLE
Request for Proper Running Steps Documentation

### ISSUE THREAD

**Issue by rajkumardongre** [Chebart/Transformer-Based-OCR#1]
I recently tried to run the project and found that the documentation for running the model is not as clear as it could be. I encountered some difficulties and believe that providing more detailed and explicit running steps would greatly benefit users who are trying to set up and use the model.

Thankyou

**Comment by Chebart** [comment]
Hello, thank you for your issue. Could you please clarify at which steps you are having difficulties? Your answer will help me to create a clear usage guide.

**Comment by Atharvaraut19** [comment]
Could you please tell the steps to follow for training the model. Which all files are needed to be run and in which pattern also how to train it with the dataset.

**Comment by Chebart** [comment]
I added "Usage" section to README.md

**Comment by rajkumardongre** [comment]
Thank you so much, I will try this.
